### PR TITLE
net standard 2.0

### PR DESCRIPTION
**Pull request by rfvgyhn**
Moves library to net standard 2.0 which allows for net core usage. Changes include:
* Using the C# 7.2 `Span<T>` type instead of unsafe code
* Using `K4os.Compression.LZ4` instead of `LZ4PCL` since it's compatible with .net standard
* Move wpf app to net 4.7.2 in order to consume .net standard 2.0 lib
* Update `MahApps.Metro` and `Fody` to latest 4.7.2 versions

### CODE REVIEW

**Review by Atvaark — CHANGES_REQUESTED** [review]
Thanks. Looks good to me, but I can't test this thoroughly right now.

The W3SavegameEditor project file doesn't seem to build/restore packages on VS2017 anymone due to some messed up package references.

Are you sure about targeting the latest Framework 4.7.2 for the UI and not something more common?

**Comment by rfvgyhn** [comment]
Looks like I didn't migrate the UI project to package references properly. Should be fixed now.

As for the framework version, it could target as low as 4.6.1. Doing that requires support assemblies to be included in the final package to make up for missing BCL APIs and also assembly binding redirects. When using VS2017 15.3 or higher, the assemblies are automatically copied to the output dir (adds about 1.5MB). 4.7.1 is the first version of the framework to support all APIs without needing support assemblies and don't need the redirects. Do you have a preference on which version is used?

**Comment by Atvaark** [comment]
Either 4.6.2 or 4.7.1 should be fine.

**Comment by rfvgyhn** [comment]
Sorry for the delay. PR updated to use 4.7.1.

**Comment by Atvaark** [comment]
Looks good to me. May I ask what you are using this library for?

**Review by Atvaark — APPROVED** [review]

**Comment by rfvgyhn** [comment]
A helper app to track the collect 'em all achievement. https://github.com/Rfvgyhn/gwent-tracker

Started out with just a WPF version to learn ReactiveUI but since proton came out, I decided I'd learn a bit about F# and port it to GTK#/Xamarin so I could use it on linux. Needed a .net core compatible version for that.

**Pull request merged**
